table Sales
	lineageTag: dd7d2d60-ec1e-4117-94a3-0ef7f06d0c6c

	measure 'Sales Amount' = ```
			
			SUMX(
			    'Sales',
			    'Sales'[Quantity] * 'Sales'[UnitPrice]
			)
			
			```
		lineageTag: acfd9c01-5d07-49e2-9cf7-91bcdc29c906

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Sales Amount LY' =
			
			CALCULATE(
			    [Sales Amount],
			    SAMEPERIODLASTYEAR('Date'[Date])
			)
		lineageTag: 4ab58871-dfec-4579-a9aa-c02e82863056

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Sales Amount PM' =
			
			CALCULATE(
				[Sales Amount],
				PREVIOUSMONTH('Date'[Date])
			)
		lineageTag: 7b9e8c2d-4c5b-4d8a-8b2d-3a8e8c2d4d8a

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column CustomerKey
		dataType: int64
		formatString: 0
		lineageTag: dc27833a-ea3f-4de3-b72a-7804f8c6297b
		summarizeBy: none
		sourceColumn: CustomerKey

		annotation SummarizationSetBy = Automatic

	column StoreKey
		dataType: int64
		formatString: 0
		lineageTag: ae79b9ad-8e83-4cd9-87b3-ef5a9aba2ced
		summarizeBy: none
		sourceColumn: StoreKey

		annotation SummarizationSetBy = Automatic

	column ProductKey
		dataType: int64
		formatString: 0
		lineageTag: 96b9a837-6abf-4d54-9996-34eeec6aafc6
		summarizeBy: none
		sourceColumn: ProductKey

		annotation SummarizationSetBy = Automatic

	column Quantity
		dataType: double
		lineageTag: 7386bafc-73d6-4c5a-8eea-8842b17dc9d8
		summarizeBy: sum
		sourceColumn: Quantity

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column OrderNumber
		dataType: int64
		formatString: 0
		lineageTag: f26c3986-9492-4d8c-a187-5b830c48ee7f
		summarizeBy: sum
		sourceColumn: OrderNumber

		annotation SummarizationSetBy = Automatic

	column LineNumber
		dataType: int64
		formatString: 0
		lineageTag: 0286d9a9-c0d5-4907-9310-62c33c605961
		summarizeBy: sum
		sourceColumn: LineNumber

		annotation SummarizationSetBy = Automatic

	column OrderDate
		dataType: dateTime
		formatString: Long Date
		lineageTag: 0691c71f-0f94-42dc-a27c-c5bf150acc1d
		summarizeBy: none
		sourceColumn: OrderDate

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column DeliveryDate
		dataType: dateTime
		formatString: Long Date
		lineageTag: a3ebde37-dac1-4a66-a216-97039ad0b1a2
		summarizeBy: none
		sourceColumn: DeliveryDate

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column UnitPrice
		dataType: double
		lineageTag: c9ca6afc-d93a-4ed0-bfff-12e0f2086fa5
		summarizeBy: sum
		sourceColumn: UnitPrice

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column NetPrice
		dataType: double
		lineageTag: d5d63623-f506-440f-9399-487aa3a4294d
		summarizeBy: sum
		sourceColumn: NetPrice

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column UnitCost
		dataType: double
		lineageTag: 040c7f28-5d0a-46fd-a804-be4614132813
		summarizeBy: sum
		sourceColumn: UnitCost

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column CurrencyCode
		dataType: string
		lineageTag: e535603b-e93b-4c73-9b9c-c333a6f27d89
		summarizeBy: none
		sourceColumn: CurrencyCode

		annotation SummarizationSetBy = Automatic

	column ExchangeRate
		dataType: double
		lineageTag: e69739e2-52d9-4507-b609-316b2a6012ea
		summarizeBy: sum
		sourceColumn: ExchangeRate

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition Sales = m
		mode: import
		source =
				let
				    Source = PowerPlatform.Dataflows(null)
				        {[Id="Workspaces"]}[Data]
				        {[workspaceId="0f694e77-2b7f-4efd-8c1e-401276b32219"]}[Data]
				        {[dataflowId="b7553d7c-cec1-4e1d-91ea-15a12c336b99"]}[Data]
				        {[entity="Sales",version=""]}[Data]
				in
				    Source

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

